replicaCount: 3
fullnameOverride: "ignition-app"

ignition:
  service:
    port: 8088
    nodePort: 38088
  port: 8088
  image:
    repository: inductiveautomation/ignition
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
  env:
    ACCEPT_IGNITION_EULA: 'Y'
    GATEWAY_ADMIN_PASSWORD: password
    GATEWAY_JDBC_RELINK: 'true'
    IGNITION_EDITION: full
    TZ: "America/Edmonton"

postgresql:
  service:
    port: 5432
    nodePort: 30082
  port: 5432
  image: postgres:latest
  env:
    POSTGRES_DB: ignitiondb
    POSTGRES_USER: ignitionuser
    POSTGRES_PASSWORD: ignitionpass

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: ignition
            servicePort: 8088
        - path: /db
          pathType: Prefix
          backend:
            serviceName: postgresql
            servicePort: 5432
  tls: []
