replicaCount: 3
#fullnameOverride: "ignition-app"
namespace: ignition-ns

ignition:
  nameOverride: "ignition"
  fullnameOverride: "ignition-app"
  labels:
    app: ignition
  tier: frontend
  replicaCount: 3
  service:
    port: 8088
    nodePort: 30088
  port: 8088
  image:
    repository: inductiveautomation/ignition
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
  env:
    ACCEPT_IGNITION_EULA: 'Y'
    GATEWAY_ADMIN_PASSWORD: password
    GATEWAY_JDBC_RELINK: 'true'
    IGNITION_EDITION: full
    TZ: "America/Edmonton"

postgresql:
  nameOverride: "postgresql"
  fullnameOverride: "postgresql-db"
  labels:
    app: db
  tier: backend
  replicaCount: 3
  service:
    port: 5432
    nodePort: 30432
  port: 5432
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  env:
    POSTGRES_DB: ignitiondb
    POSTGRES_USER: ignitionuser
    POSTGRES_PASSWORD: ignitionpass
  resources:
    limits:
      memory: "256Mi"
      cpu: "500m"

ingress:
  enabled: false
#   annotations: {}
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             serviceName: ignition
#             servicePort: 8088
#         - path: /db
#           pathType: Prefix
#           backend:
#             serviceName: postgresql
#             servicePort: 5432
#   tls: []
