apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ignition-app.fullname" . }}
  labels:
    {{- include "ignition-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ignition-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ignition-app.name" . }}
    spec:
      containers:
        - name: ignition
          image: "{{ .Values.ignition.image.repository }}:{{ .Values.ignition.image.tag }}"
          imagePullPolicy: {{ .Values.ignition.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.ignition.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.ignition.port }}
          resources:
            limits:
              memory: {{ .Values.ignition.resources.limits.memory }}
              cpu: {{ .Values.ignition.resources.limits.cpu }}
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          env:
            {{- range $key, $value := .Values.postgresql.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
