apiVersion: v1
kind: Service
metadata:
  name: ignition-app
  namespace: ignition-namespace
  labels:
    app: ignition-app
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: ignition-app