{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ignition-app-ingress
  namespace: ignition-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ignition
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ignition
                port:
                  number: 8088
    - host: postgresql
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgresql
                port:
                  number: 5432