apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignition-app.fullname" . }}
  labels:
    {{- include "ignition-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.ignition.service.port }}
      nodePort: {{ .Values.ignition.service.nodePort }}
      protocol: TCP
      name: ignition-tcp 
  selector:
    app: {{ include "ignition-app.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.postgresql.service.port }}
      nodePort: {{ .Values.postgresql.service.nodePort }}
      protocol: TCP
      name: ignition-db
  selector:
    app: {{ include "postgresql.name" . }}