apiVersion: apps/v1
kind: Deployment
metadata:
  name:  webdeploy
  labels:
    name:  webdeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      server: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        server: web
    spec:
      containers:
      - name: webserver
        image: httpd:2.4
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
          - containerPort: 80


---


apiVersion: v1
kind: Service
metadata:
  name: websrvc
spec:
  selector:
    server: web
  type:  ClusterIP
  ports:
  - port:  8080
    targetPort:  80


---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
      name: web-ingress
spec:
  rules:
  - host: mysite.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: websrvc
            port:
              number: 8080