apiVersion: apps/v1
kind: Deployment
metadata:
    name: ignition-depl
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: ignition

    template:
        metadata:
            labels:
                app: ignition

        spec:
          volumes:
              - name: ignition-storage
                persistentVolumeClaim:
                  claimName: ignition-pv-claim
          containers:
            - name: ignition
              image: kcollins/ignition:latest
              env:
                - name: GATEWAY_ADMIN_PASSWORD
                  value: password
                - name: GATEWAY_JDBC_RELINK
                  value: 'true'
                - name: IGNITION_EDITION
                  value: full
                - name: TZ
                  value: "America/Edmonton"
              ports:
                - containerPort: 8088
              volumeMounts:
                - name: ignition-storage                      
                  mountPath: /data  
              resources:
                limits:
                  memory: "1Gi"
                  cpu: "1"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ignition-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
    name: ignition-ip
spec:
    type: LoadBalancer
    selector:
        app: ignition
    ports:
      - protocol: TCP
        port: 8088
        targetPort: 8088
        nodePort: 30088